"""
Configuration file for wkhtmltopdf path.
This file is generated by the install_wkhtmltopdf.py script.
You can manually edit this file if the path to wkhtmltopdf changes.
"""

# Path to wkhtmltopdf executable
WKHTMLTOPDF_PATH = r"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe"
